@api = http://localhost:3000/parkings

### Obtener todos los parkings
GET {{api}}

###
### Obtener un parking por su ID
GET {{api}}/1

###
### Obtener el conteo total de parkings
GET {{api}}/count

###
POST {{api}}

Content-Type: application/json
{
    "parking_number": 1,
    "parking_location": "Ejemplo de ubicación",
    "parking_capacity": 50
}

###
### Eliminar un parking por su ID
DELETE {{api}}/2

###
### Actualizar la información de un parking existente
PUT {{api}}/2
Content-Type: application/json
{
    "parking_number": 2,
    "parking_location": "Nueva ubicación",
    "parking_capacity": 60,
    "fk_client": 2,
    "fk_status": 2
}
