@api = http://localhost:3000/users

GET {{api}}
###
POST http://localhost:3000/login

Content-Type: application/json
{
    "emai": "kevin12@gmail.com",
    "password": "kevin12"
}
###
GET  {{api}}/1

###
GET {{api}}/count

###
POST  {{api}}

Content-Type: application/json
{
    "first_name": "John",
    "last_name": "Doe",
    "password": "examplepassword",
    "email": "john.doe@example.com",
    "nickname": "johndoe",
    "category": "A",
    "accessCode": "123456"
}

###
DELETE {{api}}/2

###
PUT {{api}}/2

Content-Type: application/json
{
    "first_name": "Jane",
    "last_name": "Doe",
    "password": "updatedpassword",
    "email": "jane.doe@example.com",
    "nickname": "janedoe",
    "category": "B",
    "accessCode": "654321"
}
