@api = http://localhost:3000/employees

### Obtener todos los empleados
GET {{api}}

###

### Obtener un empleado por su ID
GET {{api}}/1

###

### Obtener el conteo total de empleados
GET {{api}}/count

###

### Agregar un nuevo empleado
POST {{api}}
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@example.com",
    "position": "Manager",
    "department": "Sales"
}

###

### Eliminar un empleado por su ID
DELETE {{api}}/2

###

### Actualizar la información de un empleado existente
PUT {{api}}/2
Content-Type: application/json

{
    "first_name": "Jane",
    "last_name": "Doe",
    "email": "jane.doe@example.com",
    "position": "Supervisor",
    "department": "Marketing"
}
