@api = http://localhost:3000/visits

GET {{api}}
###
POST http://localhost:3000/login

Content-Type: application/json
{
    "email": "kevin12@gmail.com",
    "password": "kevin12"
}
###
GET  {{api}}/1

###
GET {{api}}/count

###
POST  {{api}}

Content-Type: application/json
{
    "visit_company": "Company ABC",
    "visit_reason": "Meeting",
    "visit_name": "John",
    "visit_lastName": "Doe",
    "fk_client": null,
    "fk_status": 1
}

###
DELETE {{api}}/2

###
PUT {{api}}/2

Content-Type: application/json
{
    "visit_company": "Company XYZ",
    "visit_reason": "Consultation",
    "visit_name": "Jane",
    "visit_lastName": "Doe",
    "fk_client": 3,
    "fk_status": 2
}
